name: Check Docstrings
inputs:
    python-version:
        description: 'The version of Python to use for the workflow.'
        default: '3.10'
        required: false
        type: string
    repository:
        description: 'The repository to check the docstrings for.'
        required: True
        type: string
    branch:
        description: 'The branch to check the docstrings for.'
        required: false
        type: string
        default: ''
    package-name:
        description: 'The name of the package to check the docstrings for.'
        required: True
        type: string
    names-to-skip:
        description: 'The names of the modules/classes/functions/methods to skip in the docstring check.'
        required: false
        type: string
        default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Global Setup
      run: |
        pip install -U pip
        pip install pytest-xdist
        git config --global user.email "CI@example.com"
        git config --global user.name "CI Almighty"
      shell: bash

    - name: Checkout Repository to be tested
      uses: actions/checkout@v2
      with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: repo_to_test

    - name: Install package
      run: python -m pip install ./repo_to_test/${{ inputs.package-name }}
      shell: bash

    - name: Run docstring check
      run: pytest tests --package=${{ inputs.package-name }} --names-to-skip=${{ inputs.names-to-skip }}
      shell: bash