name: Call Check Docstrings
on:
  workflow_dispatch:

jobs:
  check-docstrings:
    uses: catalystneuro/.github/.github/workflows/check_docstrings.yaml@docstring_tests
    with:
      python-version: '3.10'
      repository: 'catalystneuro/neuroconv'
      package-name: 'neuroconv'