name: Call Check Docstrings
on:
  workflow_dispatch:

jobs:
  check-docstrings:
    runs-on: ubuntu-latest
    name: Check Docstrings
    steps:
      - id: check_docstrings
        uses: catalystneuro/.github/check_docstrings@relax_docstrings
        with:
          python-version: '3.10'
          repository: 'catalystneuro/roiextractors'
          branch: 'test_check_docstrings'
          package-name: 'roiextractors'
          names-to-skip: 'skipped_fn'