name: Call Check Docstrings
on:
    workflow_dispatch:

jobs:
    check-docstrings:
        uses: catalystneuro/.github/workflows/check-docstrings@docstring_tests
        with:
            python-version: '3.10'
            repository: 'catalystneuro/roiextractors'
            package-name: 'roiextractors'